### ISSUE TITLE
gDrive.py giving path not found error

### ISSUE THREAD

**Issue by udaythefreelancer** [StarkGang/FridayUserbot#11]
File Not found in local server. Give me a file path :((
![Click Here to See The Proof](https://user-images.githubusercontent.com/46833234/84237812-a3dd2c80-ab17-11ea-8b99-44f0a69fa861.png)

**Comment by StarkGang** [comment]
@udaythefreelancer Put Path 🙄

**Comment by udaythefreelancer** [comment]
how
