### ISSUE TITLE
Upload folder as tree

### ISSUE THREAD

**Issue by Deshdeepak1** [StarkGang/FridayUserbot#116]
The files when uploading folder are uploaded all together. Wouldn't it be better if they are uploaded in tree format.
For e.g. if this is tree in the server,

/dir1/dir2/dir3
- dir4
- f1
- dir5
- dir6
- f2
- f3
- f4
and if we want to upload entire dir3, it should we uploaded as
dir3 (as msg)
dir3/dir4 (as msg)
f1 (as file)
dir3/dir4 (as msg)
dir3/dir5 (as msg)
dir3/dir5/dir6 (as msg)
f2 (as file)
dir3/dir5/dir6 (as msg)
f3 (as file)
dir3/dir5 (as msg)
f4 (as file)
dir3 (as msg)
Should I make aPR of that ?

**Comment by StarkGang** [comment]
What do you mean?

**Comment by Deshdeepak1** [comment]
oh sorry the indentation got removed after posting . 
I meant dir are tree like structures but  the bot uploads all the files together. Wouldn't it be better if it uploads like a tree. Sending dir names as msg and then its files as file, recursively  for sub dirs .
