### ISSUE TITLE
Feature Request: Support for music over voice chat

### ISSUE THREAD

**Issue by mubashir-rehman** [StarkGang/FridayUserbot#277]
Telegram recently launched voice chat in groups. However, there no bots that can chat over voice chat. Kindly provide a feature to use userbot(or bot) for playing music on voice chats.

**Comment by StarkGang** [comment]
> Telegram recently launched voice chat in groups. However, there no bots that can chat over voice chat. Kindly provide a feature to use userbot(or bot) for playing music on voice chats.

Currently, Telethon Doesn't Have That Feature. I don't know about raw apis or other libs, so, i am closing it.
