### ISSUE TITLE
Build failing because of pornhub api issue

### ISSUE THREAD

**Issue by vibhuj5** [StarkGang/FridayUserbot#282]
ERROR: Could not find a version that satisfies the requirement pornhub-api (from -r /tmp/build_a14723a2_/requirements.txt (line 11)) (from versions: none)
       ERROR: No matching distribution found for pornhub-api (from -r /tmp/build_a14723a2_/requirements.txt (line 11))
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by StarkGang** [comment]
please deploy as container.

**Comment by StarkGang** [comment]
i am afraid i have to close this.
