### ISSUE TITLE
Need Guide for Deploy on Heroku

### ISSUE THREAD

**Issue by NEOIR** [StarkGang/FridayUserbot#66]
Hi

# Im Deploy Your Repo on Heroku.
### 3. Whats the Bot Commands and Works ?

Thanks.

**Comment by NEOIR** [comment]
### Bot Commands ?

**Comment by spandey112** [comment]
Sad lyf

**Comment by StarkGang** [comment]
we have it check your eyes please. For more support visit @fridayot
